language: python
python: 3.6
install:
    - pip install -r requirements-ci.txt
    - pip install -e . 
    - python -m spacy download en_core_web_sm
script: pytest -vv --cov=textbot
after_success: coveralls

